sudo: required
services:
  - docker
script: docker build -t bitcored . && ( docker run bitcored -version | tee /dev/stderr | grep -q $(cat VERSION) ) 2>&1
notifications:
  email:
    on_success: never
